package com.javarevolutions.jhs.model;
// Generated 25/10/2013 05:03:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Alumnos generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int matricula;
     private Login login;
     private String nombre;
     private String app;
     private String apm;
     private int edad;
     private String sexo;
     private Date fechaRegistro;

    public Alumno() {
    }

    public Alumno(int matricula, Login login, String nombre, String app, String apm, int edad, String sexo, Date fechaRegistro) {
       this.matricula = matricula;
       this.login = login;
       this.nombre = nombre;
       this.app = app;
       this.apm = apm;
       this.edad = edad;
       this.sexo = sexo;
       this.fechaRegistro = fechaRegistro;
    }
   
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApp() {
        return this.app;
    }
    
    public void setApp(String app) {
        this.app = app;
    }
    public String getApm() {
        return this.apm;
    }
    
    public void setApm(String apm) {
        this.apm = apm;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


