package com.javarevolutions.jhs.model;
// Generated 25/10/2013 05:03:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String usuario;
     private String password;
     private String nombre;
     private Integer edad;
     private Date fecha;
     private byte[] archivo;
     private String url;
     private Set alumnoses = new HashSet(0);

    public Login() {
    }

	
    public Login(String usuario) {
        this.usuario = usuario;
    }
    public Login(String usuario, String password, String nombre, Integer edad, Date fecha, byte[] archivo, String url, Set alumnoses) {
       this.usuario = usuario;
       this.password = password;
       this.nombre = nombre;
       this.edad = edad;
       this.fecha = fecha;
       this.archivo = archivo;
       this.url = url;
       this.alumnoses = alumnoses;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public byte[] getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(byte[] archivo) {
        this.archivo = archivo;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }




}


